version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: pip install beautifulsoup4 dbf enum34
      - run: pip install nose2
      - run:
          name: Try to run nose
          command: |
            mkdir test-results
            cd py
            export PYTHONPATH=$PWD/src
            nose2
      - store_test_results:
          path: test-results
